# Generated by Django 2.2.3 on 2020-05-14 14:51

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('apikey', models.CharField(blank=True, max_length=150, null=True, verbose_name='api key')),
                ('username', models.CharField(default='未設定', max_length=100, verbose_name='user name')),
                ('thumbnail', models.ImageField(default='./userthumbnail/noimage.png', upload_to=api.models.get_thumbnail_path)),
                ('sex', models.IntegerField(default=0, verbose_name='sex')),
                ('birth', models.IntegerField(default=0, verbose_name='birth')),
                ('country', models.CharField(blank=True, max_length=5, null=True, verbose_name='country')),
                ('language', models.CharField(default='NA', max_length=5, verbose_name='language')),
                ('is_active', models.BooleanField(default='false', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined')),
            ],
            options={
                'db_table': 'appuser',
                'ordering': ('-date_joined',),
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(default='NA', max_length=5, verbose_name='language')),
                ('review_post', models.TextField(blank=True, help_text='Please enter within 140 characters.', max_length=140, null=True, verbose_name='review')),
                ('review_rating', models.FloatField(blank=True, null=True, verbose_name='rating')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_target', to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_writer', to='api.AppUser')),
            ],
            options={
                'db_table': 'review',
                'ordering': ('-date_posted',),
            },
        ),
    ]
