# Generated by Django 2.2.3 on 2020-05-23 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apikey', models.CharField(blank=True, max_length=150, null=True, verbose_name='api key')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date posted')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='like_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'like',
                'ordering': ('-date_posted',),
            },
        ),
    ]
