# Generated by Django 2.2.3 on 2019-11-11 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='spotId',
            new_name='spot',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='email',
            new_name='writer',
        ),
    ]
