# Generated by Django 2.2.3 on 2020-06-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_post',
            field=models.TextField(blank=True, help_text='Please enter within 140 characters.', max_length=500, null=True, verbose_name='review'),
        ),
    ]
