# Generated by Django 2.2.3 on 2019-10-29 04:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(help_text='30文字以内で記入してください', max_length=30, verbose_name='user name')),
                ('thumbnail', models.ImageField(default='./thumbnail/noimage.png', upload_to='thumbnail', verbose_name='thumbnail')),
                ('self_intro', models.CharField(blank=True, max_length=150, null=True, verbose_name='introduction')),
                ('major_category', models.CharField(choices=[('NA', '-'), ('MU', 'Museum'), ('AM', 'Art museum'), ('SH', 'Shrine'), ('TR', 'temple'), ('BU', 'Building'), ('AN', 'Animal and Aquarium')], default='NA', max_length=2, verbose_name='major category')),
                ('address', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='address')),
                ('telephone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Tel number must be entered in the format: "09012345678". Up to 15 digits allowed.', regex='^[0-9]+$')], verbose_name='telephone number')),
                ('entrance_fee', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='entrance fee')),
                ('business_hours', models.CharField(blank=True, help_text='Please enter within 100 characters.', max_length=100, null=True, verbose_name='business hours')),
                ('holiday', models.CharField(blank=True, help_text='Please enter within 30 characters.', max_length=30, null=True, verbose_name='holiday')),
                ('is_staff', models.BooleanField(default=False, help_text='管理サイトにログイン可能かどうか指定してください。', verbose_name='staff_status')),
                ('is_active', models.BooleanField(default='True', help_text='ユーザーがアクティブ状態か指定してください。', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exhibit_name', models.TextField(help_text='30文字以内で入力しください', max_length=30)),
                ('exhibit_desc', models.TextField(help_text='500文字以内で入力してください', max_length=500)),
                ('post_pic', models.ImageField(blank=True, upload_to='postpic/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exhibit_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exhibit',
                'ordering': ('-upload_date',),
            },
        ),
    ]
