# Generated by Django 2.2.3 on 2020-01-18 01:36

import analysis.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exhibit_csv',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.get_infference_model_path, verbose_name='exhibit csv list'),
        ),
        migrations.AddField(
            model_name='user',
            name='knn_model',
            field=models.FileField(blank=True, null=True, upload_to=analysis.models.get_infference_model_path, verbose_name='knn model'),
        ),
        migrations.AlterField(
            model_name='exhibitpicture',
            name='exhibit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibit_pk', to='analysis.Exhibit'),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(default='./thumbnail/noimage.png', upload_to=analysis.models.get_thumbnail_path, verbose_name='thumbnail'),
        ),
    ]
