# Generated by Django 2.2.3 on 2019-11-05 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='major_category',
            field=models.CharField(choices=[('NA', '-'), ('MU', '博物館'), ('AM', '美術館'), ('SH', '神社'), ('TR', '寺'), ('BU', '建築物'), ('AN', '動物園・水族館')], default='NA', max_length=2, verbose_name='major category'),
        ),
        migrations.AlterField(
            model_name='user',
            name='self_intro',
            field=models.CharField(blank=True, help_text='Please enter within 1000 characters.', max_length=1000, null=True, verbose_name='introduction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Please enter within 30 characters.', max_length=30, verbose_name='user name'),
        ),
        migrations.CreateModel(
            name='UserEn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Please enter within 30 characters.', max_length=30, verbose_name='user name')),
                ('self_intro', models.CharField(blank=True, help_text='Please enter within 1000 characters.', max_length=1000, null=True, verbose_name='introduction')),
                ('major_category', models.CharField(choices=[('NA', ''), ('MU', 'Museum'), ('AM', 'Art museum'), ('SH', 'Shrine'), ('TR', 'temple'), ('BU', 'Building'), ('AN', 'Animal and Aquarium')], default='NA', max_length=2, verbose_name='major category')),
                ('address', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='address')),
                ('entrance_fee', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='entrance fee')),
                ('business_hours', models.CharField(blank=True, help_text='Please enter within 100 characters.', max_length=100, null=True, verbose_name='business hours')),
                ('holiday', models.CharField(blank=True, help_text='Please enter within 30 characters.', max_length=30, null=True, verbose_name='holiday')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='english_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_en',
            },
        ),
    ]
