# Generated by Django 2.2.3 on 2020-02-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200118_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, help_text='※港区芝公園', max_length=50, null=True, verbose_name='address_city'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_prefecture',
            field=models.CharField(blank=True, help_text='※東京都', max_length=20, null=True, verbose_name='address_pre'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_street',
            field=models.CharField(blank=True, help_text='※4-2-8', max_length=50, null=True, verbose_name='address_street'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.FloatField(blank=True, max_length=1, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.FloatField(blank=True, max_length=1, null=True, verbose_name='logitude'),
        ),
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='url'),
        ),
    ]
