# Generated by Django 2.2.3 on 2019-11-05 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20191105_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('na', ''), ('en', 'English'), ('zh', 'Chinese'), ('ko', 'Korea')], default='NA', max_length=5, verbose_name='language')),
                ('username', models.CharField(blank=True, help_text='Please enter within 30 characters.', max_length=30, null=True, verbose_name='user name')),
                ('self_intro', models.CharField(blank=True, help_text='Please enter within 1000 characters.', max_length=1000, null=True, verbose_name='introduction')),
                ('major_category', models.CharField(choices=[('NA', ''), ('MU', 'Museum'), ('AM', 'Art museum'), ('SH', 'Shrine'), ('TR', 'temple'), ('BU', 'Building'), ('AN', 'Animal and Aquarium')], default='NA', max_length=2, verbose_name='major category')),
                ('address', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='address')),
                ('entrance_fee', models.CharField(blank=True, help_text='Please enter within 150 characters.', max_length=150, null=True, verbose_name='entrance fee')),
                ('business_hours', models.CharField(blank=True, help_text='Please enter within 100 characters.', max_length=100, null=True, verbose_name='business hours')),
                ('holiday', models.CharField(blank=True, help_text='Please enter within 30 characters.', max_length=30, null=True, verbose_name='holiday')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='english_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userlang',
            },
        ),
        migrations.DeleteModel(
            name='UserEn',
        ),
    ]
