# Generated by Django 2.2.3 on 2020-02-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20200212_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlang',
            name='address_city',
            field=models.CharField(blank=True, help_text='※港区芝公園', max_length=50, null=True, verbose_name='address_city'),
        ),
        migrations.AddField(
            model_name='userlang',
            name='address_prefecture',
            field=models.CharField(blank=True, help_text='※東京都', max_length=20, null=True, verbose_name='address_pre'),
        ),
        migrations.AddField(
            model_name='userlang',
            name='address_street',
            field=models.CharField(blank=True, help_text='※4-2-8', max_length=50, null=True, verbose_name='address_street'),
        ),
    ]
