# Generated by Django 2.2.3 on 2019-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20191105_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_desc_en',
            field=models.TextField(default='', help_text='500文字以内で入力してください', max_length=500),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_desc_zh',
            field=models.TextField(default='', help_text='500文字以内で入力してください', max_length=500),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_name_en',
            field=models.TextField(default='', help_text='30文字以内で入力しください', max_length=30),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='exhibit_name_zh',
            field=models.TextField(default='', help_text='30文字以内で入力しください', max_length=30),
        ),
    ]
