# Generated by Django 2.2.3 on 2020-05-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200212_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlang',
            name='address',
        ),
    ]
