# Generated by Django 2.2.3 on 2019-11-06 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20191106_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_desc_en',
            field=models.TextField(blank=True, default='', help_text='500文字以内で入力してください', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_desc_zh',
            field=models.TextField(blank=True, default='', help_text='500文字以内で入力してください', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_name_en',
            field=models.TextField(blank=True, default='', help_text='30文字以内で入力しください', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_name_zh',
            field=models.TextField(blank=True, default='', help_text='30文字以内で入力しください', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userlang',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userlang', to=settings.AUTH_USER_MODEL),
        ),
    ]
