# Generated by Django 2.2.3 on 2020-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_remove_userlang_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating_amount',
            field=models.IntegerField(default=0, verbose_name='rating amount'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_sum',
            field=models.IntegerField(default=0, verbose_name='rating sum'),
        ),
    ]
