# Generated by Django 2.2.3 on 2020-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20200614_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='exhibit_desc',
            field=models.TextField(help_text='1000文字以内で入力してください', max_length=1000),
        ),
    ]
